package com.leetcode.easy;

/**
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 *
 * @Auther: jinsheng.wei
 * @Description:
 */
public class FindTheDifference {

    public static void main(String[] args) {
        String s = "abcd", t = "abcde";
        System.out.println(findTheDifference(s, t));
    }

    public static char findTheDifference(String s, String t) {
        int[] baseNums = new int[26];
        for(int i = 0; i < s.length(); i++){
            int index = s.charAt(i) - 'a';
            baseNums[index] += 1;
        }

        char retChar = ' ';
        for(int i = 0; i < t.length(); i ++){
            int index  = t.charAt(i) - 'a';
            baseNums[index] -= 1;
            if(baseNums[index] == -1){
                retChar = t.charAt(i);
                break;
            }
        }

        return retChar;
    }
}
